name: Build iOS Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Prebuild iOS project
        run: npx expo prebuild --platform ios

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: List Xcode schemes (debug)
        run: |
          ls ios
          xcodebuild -workspace ios/*.xcworkspace -list

      - name: Build unsigned IPA
        run: |
          xcodebuild -workspace ios/<YOUR_WORKSPACE_NAME>.xcworkspace \
            -scheme <YOUR_SCHEME_NAME> \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            clean archive \
            -archivePath $PWD/build/app.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

          mkdir -p build/ipa

          echo '<?xml version="1.0" encoding="UTF-8"?> 
          <plist version="1.0">
